#!/bin/bash

if [[ -f ~/.ssh/id_rsa_agent ]]; then
    eval $(ssh-agent -s)
    cp ~/.ssh/id_rsa_agent ~/id_rsa_agent
    chmod 0400 ~/id_rsa_agent
    ssh-add ~/id_rsa_agent
    echo -n `ssh-add -L`
    echo -n " `ssh-add -l`"
    echo " `whoami`@${HOSTNAME}"
fi

$@
